# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ClouText' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ClouText
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

end
